apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: enlight-staging
  labels:
    app: fastapi
    app.kubernetes.io/part-of: enlight-lab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        team: enlight-demo
        env: staging
    spec:
      containers:
        - name: api
          image: kirtiprasad2003/enlight-fastapi:demo-pass
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
