apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{SERVICE_NAME}}
  namespace: argocd
spec:
  project: enlight-lab
  source:
    repoURL: https://github.com/kirtiprasad2003/enlight-lab-platform.git
    targetRevision: main
    path: workload/scaffolded/{{SERVICE_NAME}}/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: enlight-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
