apiVersion: v1
kind: Secret
metadata:
  name: robusta-secrets
  namespace: robusta
type: Opaque
stringData:
  SIGNING_KEY: 2a3510c6-27e0-4ca4-a1d9-58800ed9822d
  ROBUSTA_UI_TOKEN: eyJhY2NvdW50X2lkIjogImU5MmI1ODg1LTUyNmUtNDgwNS05MTcyLWEwN2UwODExZWZiYSIsICJhcGlfa2V5IjogImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp5YjJ4bElqb2lZVzV2YmlJc0ltbGhkQ0k2TVRZeU5ERTNNalF5TkN3aVpYaHdJam94T1RNNU56UTROREkwZlEuaFJMdjZQQW54MWNhdkR3bC1pWXlnQXJINHFBMERWSFluckQ3MUFzcXFQdyIsICJzdG9yZV91cmwiOiAiaHR0cHM6Ly9zcC5yb2J1c3RhLmRldiIsICJlbWFpbCI6ICJhcGl1c2VyLUVubGlnaHRsYWIwMS02NzI4NTJAcm9idXN0YS5kZXYiLCAicGFzc3dvcmQiOiAiNWQ3NWJiZDEtMmJlMi00YWY1LTgxMzEtNGZlOTI0NjhiYzAxIn0=
