# Demo 3 - Create GitHub PR with scaffolded service bundle
#Requires -Version 5.1
param(
    [string]$ServiceName = "auto",
    [string]$Repo = "kirtiprasad2003/enlight-lab-platform",
    [string]$BaseBranch = "main"
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "idp-state.ps1")
$Root = Get-IdpRoot
if ($ServiceName -in @("auto", "", "demo-api")) {
    $ServiceName = Get-IdpLastService
    if (-not $ServiceName) { throw "No scaffolded service. Run Scaffold first." }
}
$ScaffoldDir = Join-Path $Root "workload\scaffolded\$ServiceName"
$Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$Branch = "idp/scaffold-$ServiceName-$Stamp"

if (-not (Test-Path $ScaffoldDir)) {
    throw "Scaffold not found. Run Scaffold first."
}

$mcpPath = "$env:USERPROFILE\.cursor\mcp.json"
if (-not (Test-Path $mcpPath)) { throw "GitHub token not found in mcp.json" }
$token = (Get-Content $mcpPath -Raw | ConvertFrom-Json).mcpServers.github.env.GITHUB_PERSONAL_ACCESS_TOKEN
$headers = @{
    Authorization          = "Bearer $token"
    Accept                 = "application/vnd.github+json"
    "X-GitHub-Api-Version" = "2022-11-28"
}

Write-Host ""
Write-Host "=== Demo 3: Create PR (publish:github simulation) ===" -ForegroundColor Cyan
Write-Host "Service: $ServiceName" -ForegroundColor Yellow
Write-Host "SERVICE_NAME: $ServiceName" -ForegroundColor Gray
Write-Host "Branch:  $Branch" -ForegroundColor Gray
Write-Host ""

# Always add a small IDP run stamp so repeat demos still open a fresh PR on GitHub
$runFile = Join-Path $ScaffoldDir "IDP-DEMO-RUN.md"
@"
# IDP demo run $Stamp

Service: ``$ServiceName``
Generated by Enlight IDP golden path (client demo).

This file proves a new reviewable PR on each demo click.
"@ | Set-Content -Path $runFile -Encoding UTF8

Push-Location $Root
$prevErr = $ErrorActionPreference
$ErrorActionPreference = "SilentlyContinue"
try {
    git fetch origin $BaseBranch 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "git fetch failed" }

    git checkout -B $Branch "origin/$BaseBranch" 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "git checkout failed" }

    git add "workload/scaffolded/$ServiceName"
    git add "gitops/argocd/applications/$ServiceName.yaml" -f 2>$null
    $ciDest = ".github/workflows/$ServiceName-ci.yml"
    $ciSrc = "workload/scaffolded/$ServiceName/ci/$ServiceName-ci.yml"
    if (Test-Path (Join-Path $Root $ciSrc)) {
        New-Item -ItemType Directory -Path (Split-Path (Join-Path $Root $ciDest) -Parent) -Force | Out-Null
        Copy-Item (Join-Path $Root $ciSrc) (Join-Path $Root $ciDest) -Force
        git add $ciDest
    }

    git commit -m "Demo 3: IDP scaffold $ServiceName ($Stamp)" 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "git commit failed - no changes to push" }

    git push -u origin $Branch 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "git push failed" }
} finally {
    $ErrorActionPreference = $prevErr
    Pop-Location
}

$prBody = @"
## Enlight Lab IDP - agent-initiated scaffold

**Service:** ``$ServiceName``  
**Run:** ``$Stamp``

### Bundle includes
- Catalog entity, K8s, monitoring, secrets, Terraform, ArgoCD app, CI

### Flow
Portal -> scaffold -> **this PR** -> merge -> ArgoCD sync -> live in catalog

*Demo PR - review before merge.*
"@
$body = @{
    title = "IDP: $ServiceName golden path ($Stamp)"
    head  = $Branch
    base  = $BaseBranch
    body  = $prBody
} | ConvertTo-Json

$pr = Invoke-RestMethod -Method Post -Uri "https://api.github.com/repos/$Repo/pulls" -Headers $headers -Body $body -ContentType "application/json"

Set-IdpLastBranch $Branch

Write-Host "RESULT: PR created" -ForegroundColor Green
Write-Host "BRANCH: $Branch" -ForegroundColor Gray
Write-Host "  PR #$($pr.number): $($pr.html_url)" -ForegroundColor Cyan
  Write-Host "  CI workflow $ServiceName-ci will run on this PR" -ForegroundColor Gray
Write-Host "Open: $($pr.html_url)/checks" -ForegroundColor Cyan
Write-Host ""

[PSCustomObject]@{
    number    = $pr.number
    url       = $pr.html_url
    checksUrl = "$($pr.html_url)/checks"
    branch    = $Branch
    service   = $ServiceName
}
